export const TYPES = {
    ADD_HISTORY_QUERY: 'ADD_HISTORY_QUERY',
    SET_ROLES: 'SET_ROLES',
    SET_USERINFO: 'SET_USERINFO',
    SET_CONFIG: 'SET_CONFIG',
    SET_TOKEN: 'SET_TOKEN',
    LOGOUT: 'LOGOUT',
    // layout module
    COLLAPSE_LEFT: 'COLLAPSE_LEFT',
    COLLAPSE_RIGHT: 'COLLAPSE_RIGHT',
    SET_NOT_READ_MESSAGES: 'SET_NOT_READ_MESSAGES',


    SET_CURRENT_DIR: 'SET_CURRENT_DIR',
    SET_HOME_PATH: 'SET_HOME_PATH',
    SET_CURRENT_PATH: 'SET_CURRENT_PATH',
    SET_DIRS: 'SET_DIRS',
    SET_SHELL: 'SET_SHELL',
    SET_CURRENT_PARSE_PATH: 'SET_CURRENT_PARSE_PATH',
}
export default {}
